### PR TITLE
Fix deserialization of optional non-nullable fields with default values

### LINKED ISSUE #18: Deserialization of object without default values
Deserializing EJSON without a value for an _non-nullable property with default value_ fails. 

Given the following class
```
@Serializable
data class OptionalFieldsWithDefaults(
    val string: String = "Hello, world!"
)
```
This code:
```
EJson.decodeFromString<OptionalFieldsWithDefaults>("{}")
```
Will throw
```
Could not decode field 'string': Value expected to be of type STRING is of unexpected type NULL
kotlinx.serialization.SerializationException: Could not decode field 'string': Value expected to be of type STRING is of unexpected type NULL
	at app//org.mongodb.kbson.serialization.ClassBsonDecoder.rethrowAsSerializationException(BsonDecoder.kt:242)
	at app//org.mongodb.kbson.serialization.BsonDecoder.decodeString(BsonDecoder.kt:132)
	at app//kotlinx.serialization.encoding.AbstractDecoder.decodeStringElement(AbstractDecoder.kt:58)
	at app//org.mongodb.kbson.EjsonTest$OptionalFieldsWithDefaults$$serializer.deserialize(EjsonTest.kt:526)
	at app//org.mongodb.kbson.EjsonTest$OptionalFieldsWithDefaults$$serializer.deserialize(EjsonTest.kt:526)
	at app//kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257)
	at app//kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at app//org.mongodb.kbson.serialization.BsonDecoder.decodeSerializableValue(BsonDecoder.kt:100)
	at app//org.mongodb.kbson.serialization.SerializersKt.readBson(Serializers.kt:93)
	at app//org.mongodb.kbson.serialization.EJson.decodeFromBsonValue(Serializers.kt:189)
	at app//org.mongodb.kbson.serialization.EJson.decodeFromString(Serializers.kt:199)
```

Tests can be found in https://github.com/mongodb/kbson/commit/a5ae3a7048866ec0861fda832f61a85bb831e47d

### PR DESCRIPTION
**Pull request by rorbech**
Closes #18

### CODE REVIEW

File: src/commonMain/kotlin/org/mongodb/kbson/serialization/BsonDecoder.kt [hunk 1]
```diff
@@ -220,14 +235,19 @@ internal class ClassBsonDecoder(
      * [bsonDocument] that represents the class.
      */
     override fun decodeElementIndex(descriptor: SerialDescriptor): Int {
-        return if (decodedElementCount < descriptor.elementsCount) {
-            decodedElementCount++.also {
-                entryKey = descriptor.getElementName(it)
-                isOptional = descriptor.isElementOptional(it)
+        while (decodedElementCount < descriptor.elementsCount) {
```
Comment (rozza) [inline src/commonMain/kotlin/org/mongodb/kbson/serialization/BsonDecoder.kt:238]: I don't fully understand the need for a while loop here. Can you clarify?

**Review by rozza — COMMENTED** [review]
One question :)

File: src/commonMain/kotlin/org/mongodb/kbson/serialization/BsonDecoder.kt (hunk 1 above)
Comment (rorbech) [reply src/commonMain/kotlin/org/mongodb/kbson/serialization/BsonDecoder.kt:238]: `decodeElementIndex` should return the next index to decode. With this update I keep incrementing the `decodeElementCount` until we find a descriptor that is either non-optional (in which case we must decode it) or has a value (in which case we should decode even though it is optional). If selected for decoding we return the index and the method will be invoked again after decoding and will continue the search from where we left. If an element is optional and don't have a value we want to keep examining the next element in the descriptor. This goes on until have reached the end, hence the `while`-loop. 

The previous implementation returned the index of optional elements even though there weren't values in the bson document. This caused errors when trying to decode non-existent values as it tried to assign `null` to non-nullable properties.
